ARG version=bullseye
ARG node_version=18

# Accept build args
ARG gcc_install

FROM node:${node_version}-${version}

RUN echo "deb http://deb.debian.org/debian bullseye-backports main" >> /etc/apt/sources.list && \
    apt update && \
    apt install -y --no-install-recommends \
        build-essential \
        libssl-dev \
        ninja-build \
        ${gcc_install} && \
    apt install -y -t bullseye-backports cmake && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app/
