ARG version=trixie
ARG node_version=24

# Accept build args
ARG gcc_install

FROM node:${node_version}-${version}

RUN echo "deb https://deb.debian.org/debian trixie-backports main" >> /etc/apt/sources.list && \
    apt update && \
    apt install -y --no-install-recommends \
        build-essential \
        libssl-dev \
        ninja-build \
        ${gcc_install} && \
    apt install -y --no-install-recommends -t trixie-backports cmake && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/app/
