ARG version=3.16
ARG node_version=18
FROM node:${node_version}-alpine${version}
RUN apk add \
    build-base \
    openssl-libs-static \
    openssl-dev \
    cmake \
    ninja \
    $gcc_install

WORKDIR /usr/app/
