ARG version=bullseye
ARG node_version=18
FROM node:${node_version}-${version}
RUN apt update

RUN apt install -y \
    build-essential \
    libssl-dev \
    cmake \
    ninja-build \
    $gcc_install

WORKDIR /usr/app/
