name: Build - Mac M1

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-14
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4
      - name: Install OpenSSL
        run: HOMEBREW_NO_INSTALL_CLEANUP=1 brew reinstall openssl@3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm install --ignore-scripts
        env:
          CI: true
      - name: Build
        run: npx cmake-js build
        env:
          CI: true
          OPENSSL_ROOT_DIR: /opt/homebrew/opt/openssl@3
          OPENSSL_LIBRARIES: /opt/homebrew/opt/openssl@3/lib
      - name: Test
        run: npm run test
        env:
          CI: true
      - name: Package Platform
        run: node scripts/prepare-platform-packages.js darwin-arm64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-darwin-arm64
          path: npm/darwin-arm64
