name: Build - Win - Arm64

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - v*

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-windows:
    runs-on: windows-2022
    strategy:
      matrix:
        node-version: [18]
        arch: [x64, x86, arm64]
        include:
          - arch: x64
            vcpkg_triplet: x64-windows-static
            msvc_arch: amd64
          - arch: x86
            vcpkg_triplet: x86-windows-static
            msvc_arch: amd64_x86
          - arch: arm64
            vcpkg_triplet: arm64-windows-static
            msvc_arch: amd64_arm64

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set Up MSVC for Cross Compilation
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Install vcpkg
        run: |
          git submodule update --init --recursive vcpkg
          .\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: setup vcpkg
        run: |
          .\vcpkg\vcpkg install --triplet ${{ matrix.vcpkg_triplet }}
        shell: cmd

      - name: Install npm dependencies
        run: |
          npm install --ignore-scripts

      - name: Build for ${{ matrix.arch }}
        run: |
           node_modules/.bin/prebuild -r napi --upload -u ${{ secrets.GITHUB_TOKEN }} --backend cmake-js
        env:
          OPENSSL_ROOT_DIR: ${{ github.workspace }}/vcpkg/installed/${{ matrix.vcpkg_triplet }}
          OPENSSL_LIBRARIES: ${{ github.workspace }}/vcpkg/installed/${{ matrix.vcpkg_triplet }}/lib
          OPENSSL_INCLUDE_DIR: ${{ github.workspace }}/vcpkg/installed/${{ matrix.vcpkg_triplet }}/include
