name: Build - Win

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Windows ${{ matrix.arch }}
    runs-on: windows-2022
    strategy:
      matrix:
        include:
          - arch: x64
            node_arch: x64
            msvc_arch: x64
            vcpkg_triplet: x64-windows-static
            node_version: 24
          - arch: arm64
            node_arch: arm64
            msvc_arch: amd64_arm64
            vcpkg_triplet: arm64-windows-static
            node_version: 24

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc_arch }}

      - name: Setup vcpkg
        run: |
          C:\vcpkg\bootstrap-vcpkg.bat
        shell: cmd

      - name: Install OpenSSL
        run: |
          C:\vcpkg\vcpkg install openssl:${{ matrix.vcpkg_triplet }}
        shell: cmd

      - name: Disable Pre-installed Runner OpenSSL
        run: |
          if exist "C:\Program Files\OpenSSL" ren "C:\Program Files\OpenSSL" "OpenSSL_disabled"
          if exist "C:\Program Files (x86)\OpenSSL" ren "C:\Program Files (x86)\OpenSSL" "OpenSSL_disabled"
        shell: cmd

      - name: NPM Install
        run: |
          npm install --ignore-scripts
        shell: cmd

      - name: Build
        run: |
          npx cmake-js build -a ${{ matrix.node_arch }} --CDCMAKE_TOOLCHAIN_FILE="C:\vcpkg\scripts\buildsystems\vcpkg.cmake" --CDVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }} --CDCMAKE_PREFIX_PATH="C:\vcpkg\installed\${{ matrix.vcpkg_triplet }}"
        shell: cmd

      - name: Package Platform
        run: |
          node scripts/prepare-platform-packages.js win32-${{ matrix.node_arch }}-msvc
        shell: cmd

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-win32-${{ matrix.node_arch }}-msvc
          path: npm/win32-${{ matrix.node_arch }}-msvc
