name: Build - Win - Arm64

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     - v*

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build-windows-arm64:
    runs-on: windows-11-arm
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4
      - name: Install OpenSSL
        run: choco install openssl -y
      - name: Node version
        run: node --version
      - name: Build
        run: npm install --build-from-source
        env:
          CI: true
      # - name: Test
      #   run: npm run test
      #   env:
      #     CI: true
      - name: Upload
        run: node_modules/.bin/prebuild -r napi --upload -u ${{ secrets.GITHUB_TOKEN }}
        env:
          CI: true
