name: Build - Mac x64

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install --ignore-scripts
        env:
          CI: true

      - name: Build OpenSSL for macOS x64
        run: |
          git clone --depth 1 -b openssl-3.3.1 https://github.com/openssl/openssl.git _openssl_src
          cd _openssl_src
          ./Configure darwin64-x86_64-cc no-shared no-unit-test no-tests --prefix=$(pwd)/../_openssl_x64 --libdir=lib
          make -j$(sysctl -n hw.ncpu)
          make install_sw
          cd ..

      - name: Build x64 Addon
        run: |
          npx cmake-js build --arch=x64 --CDCMAKE_OSX_ARCHITECTURES=x86_64 --CDOPENSSL_ROOT_DIR="$(pwd)/_openssl_x64" --CDOPENSSL_USE_STATIC_LIBS=TRUE
        env:
          CI: true

      - name: Package Platform
        run: node scripts/prepare-platform-packages.js darwin-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-darwin-x64
          path: npm/darwin-x64
